### ISSUE TITLE
Create requirements for database

### ISSUE THREAD

**Issue by mwatts15** [mwatts15/PyOpenWorm#3]

**Comment by slarson** [comment]
Looks like a start on this is [over here](https://github.com/mwatts15/openworm_docs/blob/master/process.rst)

**Comment by slarson** [comment]
I think it would be helpful if we can include draft method signatures and minimal python docs for each method signature that we plan to write in this document.  This then would constitute a specification for what will get written for the rest of the summer and leave you with lots of freedom to play with technologies or different implementations of this spec.

**Comment by mwatts15** [comment]
See #4.

**Comment by slarson** [comment]
I think this can be closed now.
