### ISSUE TITLE
Add lineage data to database

### ISSUE THREAD

**Issue by mwatts15** [mwatts15/PyOpenWorm#8]

**Comment by mwatts15** [comment]
Cell lineage names without immediately obvious corrections: http://pastebin.com/biQ8dZuQ
Either the name doesn't appear elsewhere in the data or I'm questioning the meaning of comma versus, slash, versus 'or' in the lineage names. Is it ambiguity in tracing the development, differences between male and hermaphrodite, or different growth patterns in different worms?

**Comment by mwatts15** [comment]
@slarson, @balicea: Just linking you guys on this.

**Comment by slarson** [comment]
@mwatts15 can you link the spreadsheet we are working off of again so I can see the bad names in context?  Already lost that file unfortunately! :)

**Comment by slarson** [comment]
@mwatts15 on second thought, can we close this issue and just work off of this one?

https://github.com/openworm/PyOpenWorm/issues/7#issuecomment-45401916

Please post your comment on the bad names over there.  Much better consolidation of effort.
